kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: binding
rules:
- apiGroups: ["bindings.kyma-project.io"]
  resources: ["bindings", "targetkinds"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: binding
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: binding
subjects:
- kind: ServiceAccount
  name: binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: binding
