# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
  pull_request:
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Prepare k3s and helm 3
        run: |
          ./ci/create-cluster-k3s.sh
          echo "Installing helm"
          curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done        
      - name: Install Bindings component using Helm
        run: |
          helm install bindings ./resources/binding
      - name: Apply test scenario and check deployment
        run: |
          ./ci/bindings/create-scenario.sh
          sleep 30
          kubectl get pods --selector=app=sandbox -oyaml 

