name: Binding-pre-master

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'components/binding/*'
      - '.github/workflows/bindings-k3s.yml'

defaults:
  run:
    working-directory: components/binding


jobs:
  env:
    PR_NUMBER: ${{ github.event.number }}
    PROJECT_ID: "sap-se-cx-gopher"
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - uses: actions/checkout@v2

      - name: Go test, vet, fmt
        run:  |
          go test ./...
          go fmt -v ./...
          go vet -v ./...


      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOPHER_GCR_KEY }}
          project_id: $PROJECT_ID
          export_default_credentials: true

      - name: Build Image
        run: |
          docker build -t eu.gcr.io/$PROJECT_ID/binding:$PR_NUMBER .

      - name: Push Image
        run: |
          gcloud auth configure-docker -q
          docker push eu.gcr.io/$PROJECT_ID/binding:$PR_NUMBER

      - name: Prepare k3s and helm 3
        run: |
          ./scripts/create-cluster-k3s.sh
          echo "Installing helm"
          curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done        

      - name: Install Bindings component using Helm
        run: |
          helm install binding ./charts/binding

      - name: Apply test scenario and check deployment
        run: |
          ./scripts/create-scenario.sh
          sleep 30
          kc get po -l app=sandbox -ojson | jq '.items | .[] | .spec.containers'
